<?xml version="1.0" encoding="UTF-8"?>
<!--
 Copyright (c) 2025 Obeo.
 This program and the accompanying materials
 are made available under the terms of the Eclipse Public License v2.0
 which accompanies this distribution, and is available at
 https://www.eclipse.org/legal/epl-2.0/

 * SPDX-License-Identifier: EPL-2.0

 Contributors:
     Obeo - initial API and implementation
-->
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>ontology</groupId>
        <artifactId>ontology-parent</artifactId>
        <version>2026.6.0</version>
        <relativePath>../ontology-parent</relativePath>
    </parent>
    <artifactId>ontology-starter</artifactId>
    <name>ontology-starter</name>
    <description>Ontology Starter</description>

    <dependencies>
        <dependency>
            <groupId>org.eclipse.sirius</groupId>
            <artifactId>sirius-web-starter</artifactId>
            <version>${sirius.web.version}</version>
        </dependency>
        <dependency>
            <groupId>ontology</groupId>
            <artifactId>ontology-model</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>ontology</groupId>
            <artifactId>ontology-model-edit</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>ontology</groupId>
            <artifactId>ontology-owl</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>ontology</groupId>
            <artifactId>ontology-xls</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-autoconfigure</artifactId>
        </dependency>
        <dependency>
            <groupId>io.projectreactor</groupId>
            <artifactId>reactor-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.emf</groupId>
            <artifactId>org.eclipse.emf.common</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.emf</groupId>
            <artifactId>org.eclipse.emf.ecore</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.emf</groupId>
            <artifactId>org.eclipse.emf.edit</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.emf</groupId>
            <artifactId>org.eclipse.emf.ecore.edit</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.sirius</groupId>
            <artifactId>org.eclipse.sirius.emfjson</artifactId>
            <version>${sirius.emfjson.version}</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.sirius</groupId>
            <artifactId>sirius-components-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.sirius</groupId>
            <artifactId>sirius-components-collaborative</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.sirius</groupId>
            <artifactId>sirius-components-collaborative-diagrams</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.sirius</groupId>
            <artifactId>sirius-components-representations</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.sirius</groupId>
            <artifactId>sirius-components-diagrams</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.sirius</groupId>
            <artifactId>sirius-components-view</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.sirius</groupId>
            <artifactId>sirius-components-view-builder</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.sirius</groupId>
            <artifactId>sirius-components-view-diagram</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.sirius</groupId>
            <artifactId>sirius-components-view-emf</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.sirius</groupId>
            <artifactId>sirius-components-emf</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.sirius</groupId>
            <artifactId>sirius-components-events</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.sirius</groupId>
            <artifactId>sirius-web-domain</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.sirius</groupId>
            <artifactId>sirius-web-application</artifactId>
        </dependency>
        <!--		<dependency>-->
        <!--			<groupId>com.fasterxml.jackson.core</groupId>-->
        <!--			<artifactId>jackson-databind</artifactId>-->
        <!--		</dependency>-->
        <!--		<dependency>-->
        <!--			<groupId>com.fasterxml.jackson.core</groupId>-->
        <!--			<artifactId>jackson-annotations</artifactId>-->
        <!--			<version>2.17.2</version>-->
        <!--		</dependency>-->

        <!--        Meta-model -->
        <dependency>
            <groupId>org.obeonetwork.dsl</groupId>
            <artifactId>org.obeonetwork.dsl.entity</artifactId>
        </dependency>
        <dependency>
            <groupId>org.obeonetwork.dsl</groupId>
            <artifactId>org.obeonetwork.dsl.entity.edit</artifactId>
        </dependency>
        <dependency>
            <groupId>org.obeonetwork.dsl</groupId>
            <artifactId>org.obeonetwork.dsl.environment</artifactId>
        </dependency>
        <dependency>
            <groupId>org.obeonetwork.dsl</groupId>
            <artifactId>org.obeonetwork.dsl.environment.edit</artifactId>
        </dependency>
        <dependency>
            <groupId>org.obeonetwork.dsl</groupId>
            <artifactId>org.obeonetwork.dsl.technicalid</artifactId>
        </dependency>
        <dependency>
            <groupId>org.obeonetwork.dsl</groupId>
            <artifactId>org.obeonetwork.dsl.technicalid.edit</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.emf.cdo</groupId>
            <artifactId>org.eclipse.emf.cdo</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.emf.cdo</groupId>
            <artifactId>org.eclipse.emf.cdo.common</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.net4j.util</groupId>
            <artifactId>org.eclipse.net4j.util</artifactId>
        </dependency>
    </dependencies>
</project>
