# Copyright (c) 2026 Obeo.
# This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
# 
# SPDX-License-Identifier: EPL-2.0
# 
# Contributors:
#     Obeo - initial API and implementation

pluginName = Ontology Edit Support
providerName = www.example.org

_UI_CreateChild_text = {0}
_UI_CreateChild_text2 = {1} {0}
_UI_CreateChild_text3 = {1}
_UI_CreateChild_tooltip = Create New {0} Under {1} Feature
_UI_CreateChild_description = Create a new child of type {0} for the {1} feature of the selected {2}.
_UI_CreateSibling_description = Create a new sibling of type {0} for the selected {2}, under the {1} feature of their parent.

_UI_PropertyDescriptor_description = The {0} of the {1}

_UI_OrganizationInformation_type = Organization Information
_UI_BusinessDomain_type = Functional Area
_UI_DataSource_type = Data Source
_UI_DataOwner_type = Data Owner
_UI_Unknown_type = Object

_UI_Unknown_datatype= Value

_UI_OrganizationInformation_name_feature = Name
_UI_OrganizationInformation_businessDomains_feature = Business Domains
_UI_OrganizationInformation_dataOwners_feature = Data Owners
_UI_OrganizationInformation_dataSources_feature = Data Sources
_UI_BusinessDomain_name_feature = Name
_UI_BusinessDomain_description_feature = Description
_UI_BusinessDomain_entities_feature = Entities
_UI_DataSource_code_feature = Code
_UI_DataSource_name_feature = Name
_UI_DataSource_description_feature = Description
_UI_DataSource_entities_feature = Entities
_UI_DataOwner_code_feature = Code
_UI_DataOwner_name_feature = Name
_UI_DataOwner_description_feature = Description
_UI_DataOwner_entities_feature = Entities
_UI_Unknown_feature = Unspecified

unnamed = (unnamed)
nocode = (no code)

