name: Continuous integration

on:
  push:
    paths-ignore:
      - "CHANGELOG.adoc"
      - "README.adoc"
      - "doc/**"
    branches:
      - "**"
    tags:
      - "*"
  pull_request:
  workflow_dispatch:

env:
  AWS_DEFAULT_REGION: eu-west-3
  AWS_ACCOUNT: 307946679637
  AWS_ROLE: github-actions-ontology
  DOCKER_IMAGE: ontology
  REGISTRY: ghcr.io
  IMAGE_NAME: obeonetwork/enterprise-ontology

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        if: github.event_name != 'pull_request'
        with:
          fetch-depth: 0

      - name: Checkout
        uses: actions/checkout@v4
        if: github.event_name == 'pull_request'
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Node SDK
        uses: actions/setup-node@v3
        with:
          node-version: 18.7
          registry-url: https://npm.pkg.github.com/

      - name: Setup Java SDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: "temurin"

      - name: Setup some global environment variables
        run: |
          echo "git_describe=$(git describe)" >> $GITHUB_ENV
          echo "app_version_latest=$(grep version frontend/package.json | awk -F \" '{print $4}')" >> $GITHUB_ENV

      - name: Build the frontend packages
        run: |
          echo -e "\n//npm.pkg.github.com/:_authToken=${{ secrets.OBEO_TOKEN }}" >> .npmrc
          echo "CI=true" >> $GITHUB_ENV
          npm ci
          npm run build
        working-directory: frontend

      - name: Copy frontend artifacts
        run: |
          mkdir -p backend/ontology-frontend/src/main/resources/static
          cp -R frontend/ontology-web/dist/* backend/ontology-frontend/src/main/resources/static

      - name: Build the backend
        env:
          USERNAME: ${{ github.actor }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: mvn -U -B -e clean verify  -f backend/pom.xml --settings settings.xml

      - name: Publish the backend
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          USERNAME: ${{github.actor}}
          PASSWORD: ${{secrets.GITHUB_TOKEN}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: mvn -B deploy -DskipTests -f backend/pom.xml --settings settings.xml

      - name: Store the fat jar
        uses: actions/upload-artifact@v4
        with:
          name: application fat jar
          path: backend/ontology-application/target/ontology-application-${{ env.app_version_latest }}.jar

      - name: Extract metadata (tags, labels) for main Docker image
        id: extract-metadata
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5.7.0
        with:
          images: obeonetwork/ontology
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha

      - name: Set up Docker Buildx to use cache feature
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        id: build
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: backend/ontology-application
          load: true
          tags: ${{ steps.extract-metadata.outputs.tags }}
          labels: ${{ steps.extract-metadata.outputs.labels }}

      - name: Log in to Docker Hub
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        if: env.GITHUB_EVENT_NAME == 'push' && (env.GITHUB_REF == 'refs/heads/main' || startsWith(env.GITHUB_REF, 'refs/tags/v'))
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.DOCKER_HUB_USER }}
          password: ${{ env.DOCKER_HUB_TOKEN }}
        env:
          DOCKER_HUB_USER: ${{ secrets.ORG_DOCKER_HUB_USER }}
          DOCKER_HUB_TOKEN: ${{ secrets.ORG_DOCKER_HUB_TOKEN }}

      - name: Push Docker image
        if: env.GITHUB_EVENT_NAME == 'push' && (env.GITHUB_REF == 'refs/heads/main' || startsWith(env.GITHUB_REF, 'refs/tags/v'))
        id: push
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: backend/ontology-application
          push: true
          tags: ${{ steps.extract-metadata.outputs.tags }}
          labels: ${{ steps.extract-metadata.outputs.labels }}
